Updated dependencies and made global exception handling true
EasyMicroservices/Actions-Microservice pull request #8
Opened 2023-11-11 13:34 UTC by MahdiyarGHD

## Description

### Related issue(s)

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [ ] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-11-12 06:27 UTC, Ali-YousefiTelori requested changes

2023-11-12 06:27 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.ActionsMicroservice.Tests/CodeReviewerCheckTests.cs
> +            //AssemblyManager.AddAssemblyToReview(
Do not comment these code please

2023-11-12 06:27 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.ActionsMicroservice.WebApi/appsettings.Development.json
> +    //"local": "Server=185.191.79.5,6752;Database=Actions;User ID=sa;Password=ijm4g83iq@;TrustServerCertificate=True;"
Please remove connection string

2023-11-12 06:27 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.ActionsMicroservice.WebApi/appsettings.json
> +    //"local": "Server=185.191.79.5,6752;Database=Actions;User ID=sa;Password=ijm4g83iq@;TrustServerCertificate=True;"
Please remove connection string

2023-11-12 06:36 UTC, Mohsen-Yaghoubi approved these changes

2023-11-14 14:44 UTC, Albert-the-jit approved these changes

2023-11-15 13:42 UTC, AmirmohammadNemati approved these changes

2023-11-16 08:13 UTC, mahdidelzendeh72 approved these changes
Thanks

2023-11-16 08:32 UTC, Ali-YousefiTelori approved these changes

2023-11-16 08:33 UTC, merged